export const sqBlack = '#0C151C';
export const sqWhite = '#FDFDFD';
export const sqRed = '#FA0020';
export const sqGray = '#bfbfbf';
export const sqPink = 'rgba(250, 0, 32,30%)';
export const sqLightGray = '#e9e9e9';
export const sqDeepLightGray = '#DEDEDE';
export const sqDeepDarkGray = '#3D3E3F';
export const sqDarkGray = '#57585A';